# Neo4j
#
# Access via "http://localhost:7474"
#   (or "http://$(docker-machine ip):7474" if using docker-machine)
version: '3'
services:
  neo4j:
    image: neo4j:3.5
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"
